### ISSUE TITLE
Playbook cannot be found

### ISSUE THREAD

**Issue by GregSilverman** [walokra/docker-ansible-playbook#1]
I am trying to modify your script to run with my playbook.

I did as per your instructions and get:

```
D20151052:playbooks gms$  docker run --name ansible-playbook --rm gms/ansible-playbook --version
ansible-playbook 2.3.0.0
  config file =
  configured module search path = [u'/ansible/library']
  python version = 2.7.13 (default, Apr 20 2017, 12:13:37) [GCC 6.3.0]
``` 

Then, when I try to execute my playbook, test_ctakes.yml in its directory:

```
D20151052:playbooks gms$ pwd
/Users/gms/development/ansible/playbooks
D20151052:playbooks gms$ ls -la
total 32
drwxr-xr-x  6 gms  staff   204 Feb 19 15:29 .
drwxr-xr-x  4 gms  staff   136 Feb 19 15:29 ..
-rw-r--r--@ 1 gms  staff  6148 Feb 19 15:29 .DS_Store
drwxr-xr-x  7 gms  staff   238 Feb 19 15:15 docker-ansible-playbook
-rw-r--r--  1 gms  staff    17 Feb 15 15:38 hosts
-rw-r--r--  1 gms  staff  1173 Feb 16 17:25 test_ctakes.yml
```

as 

`docker run --rm -it -v  /Users/gms/development/ansible/playbook gms/ansible-playbook test_ctakes.yml`

I get an error: `ERROR! the playbook: test_ctakes.yml could not be found`... I did downgrade my version of sensible to 2.3.0.0, as per your directions.

Any idea why this is not working? My playbook works just fine with `ansible-playbook` on its own.

TIA!

**Comment by walokra** [comment]
I think your volume mount is missing the correct path inside docker container. I used _"-v $(pwd):/ansible/playbooks"_ which mounts the current working directory to _"/ansible/playbooks"_ in docker container which is the WORKDIR and where the ansible looks for playbooks. 

So your command should be _"docker run --rm -it -v /Users/gms/development/ansible/playbook:/ansible/playbooks gms/ansible-playbook test_ctakes.yml"_ if your playbooks are in _"/Users/gms/development/ansible/playbook"_.

I also just updated the Dockerfile to have Ansible 2.5.0.

**Comment by GregSilverman** [comment]
Oh yeah, I did figure that out a while ago. Thanks for the update though!

**Comment by rickevry** [comment]
The ansible_helper is also mapping incorrectly. It is doing:
$(pwd):/ansible_playbooks
But I think it should be:
$(pwd):/ansible/playbooks

**Comment by walokra** [comment]
Thanks for noticing. I updated helper and Readme.
