### ISSUE TITLE
Unable to to build image with Python3 and Pip3

### ISSUE THREAD

**Issue by Dhananjay-Kumar91** [walokra/docker-ansible-playbook#5]
Tried to modify the docker file to build a python3 version and python2.7 support is deprecated. Please find attached modified Dockerfile
[Dockerfile.zip](https://github.com/walokra/docker-ansible-playbook/files/4812915/Dockerfile.zip)

**Comment by walokra** [comment]
Thanks for the changes but could you please provide it via pull request or paste the contents here as code and not in zip package?
